"""Initial schema

Revision ID: 89b503817e50
Revises: 
Create Date: 2026-04-17 19:14:09.422449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89b503817e50'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('secure_token', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('INITIALIZED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'REJECTED', 'APPROVED', name='sessionstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_sessions_secure_token'), 'customer_sessions', ['secure_token'], unique=True)
    op.create_table('loan_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('maximum_amount', sa.Float(), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('calculated_emi', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['customer_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_offers_id'), 'loan_offers', ['id'], unique=False)
    op.create_table('risk_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('cv_age_estimate', sa.Float(), nullable=True),
    sa.Column('llm_behavioral_persona', sa.String(), nullable=True),
    sa.Column('llm_risk_band', sa.String(), nullable=True),
    sa.Column('final_approval_decision', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['customer_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_evaluations_id'), 'risk_evaluations', ['id'], unique=False)
    op.create_table('telemetry_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['customer_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_logs_id'), 'telemetry_logs', ['id'], unique=False)
    op.create_table('transcript_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('raw_dialogue', sa.String(), nullable=True),
    sa.Column('extracted_income', sa.Integer(), nullable=True),
    sa.Column('extracted_profession', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['customer_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_records_id'), 'transcript_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_records_id'), table_name='transcript_records')
    op.drop_table('transcript_records')
    op.drop_index(op.f('ix_telemetry_logs_id'), table_name='telemetry_logs')
    op.drop_table('telemetry_logs')
    op.drop_index(op.f('ix_risk_evaluations_id'), table_name='risk_evaluations')
    op.drop_table('risk_evaluations')
    op.drop_index(op.f('ix_loan_offers_id'), table_name='loan_offers')
    op.drop_table('loan_offers')
    op.drop_index(op.f('ix_customer_sessions_secure_token'), table_name='customer_sessions')
    op.drop_table('customer_sessions')
    # ### end Alembic commands ###
